export const Questions = [
    {
        question: "What is the capital of India?",
        optionA: "New Delhi",
        optionB: "Mumbai",
        optionC: "Gujrat",
        optionD: "Kerela",
        answer: "A",
    },
    {
        question: "Who wrote the play 'Romeo and Juliet'?",
        optionA: "Mark Twain",
        optionB: "William Shakespeare",
        optionC: "Charles Dickens",
        optionD: "Jane Austen",
        answer: "B",
    },
    {
        question: "What is the chemical symbol for water?",
        optionA: "H2O",
        optionB: "O2",
        optionC: "CO2",
        optionD: "HO",
        answer: "A",
    },
    {
        question: "Which planet is known as the Red Planet?",
        optionA: "Earth",
        optionB: "Mars",
        optionC: "Jupiter",
        optionD: "Saturn",
        answer: "B",
    },
    {
        question: "Which element has the chemical symbol 'O'?",
        optionA: "Osmium",
        optionB: "Silver",
        optionC: "Gold",
        optionD: "Oxygen",
        answer: "D",
    },
    {
        question: "What is the largest mammal in the world?",
        optionA: "Elephant",
        optionB: "Blue Whale",
        optionC: "Giraffe",
        optionD: "Hippopotamus",
        answer: "B",
    },
    {
        question: "Which country is known as the Land of the Rising Sun?",
        optionA: "China",
        optionB: "India",
        optionC: "Japan",
        optionD: "South Korea",
        answer: "C",
    },
    {
        question: "What is the smallest prime number?",
        optionA: "1",
        optionB: "2",
        optionC: "3",
        optionD: "5",
        answer: "B",
    },
    {
        question: "Which ocean is the largest?",
        optionA: "Atlantic",
        optionB: "Indian",
        optionC: "Arctic",
        optionD: "Pacific",
        answer: "D",
    },
    {
        question: "What is the square root of 64?",
        optionA: "6",
        optionB: "7",
        optionC: "8",
        optionD: "9",
        answer: "C",
    },
    {
        question: "Who painted the Mona Lisa?",
        optionA: "Vincent Van Gogh",
        optionB: "Pablo Picasso",
        optionC: "Claude Monet",
        optionD: "Leonardo da Vinci",
        answer: "D",
    }
];


